spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/graduation_project_db?useUnicode=true&charactorEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: "root"
    password: ""
    hikari:
      pool-name: DateHikariCP # ????
      minimum-idle: 5 # ???????
      idle-timeout: 1800000 # ?????????????600000?10???
      maximum-pool-size: 10 # ????????10
      auto-commit: true # ?????????????
      max-lifetime: 1800000 # ?????????0?????????1800000?30???
      connection-timeout: 30000 # ?????????30000?30??
      connection-test-query: SELECT 1 # ?????????????
  # 静态资源访问配置
  # 访问映射路径
  mvc:
    static-path-pattern: /resources/**
  web:
    resources:
      static-locations: file:D://Project/校园组队与竞赛信息服务平台/CampusTeam_ContestInformation_ServicePlatform/src/main/resources/static/img/userhead, file:D://Project/校园组队与竞赛信息服务平台/CampusTeam_ContestInformation_ServicePlatform/src/main/resources/static/img/cover,file:D://Project/校园组队与竞赛信息服务平台/CampusTeam_ContestInformation_ServicePlatform/src/main/resources/static/img/teamlogo, file:D://Project/校园组队与竞赛信息服务平台/CampusTeam_ContestInformation_ServicePlatform/src/main/resources/static/file, file:D://Project/校园组队与竞赛信息服务平台/CampusTeam_ContestInformation_ServicePlatform/src/main/resources/static/file2, file:D://Project/校园组队与竞赛信息服务平台/CampusTeam_ContestInformation_ServicePlatform/src/main/resources/static/img/article, file:D:/Project/校园组队与竞赛信息服务平台/CampusTeam_ContestInformation_ServicePlatform/src/main/resources/static/img/news

  servlet:
    multipart:
      # 最大文件大小
      max-file-size: 200MB
      # 最大请求大小
      max-request-size: 215MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yiduofar.serviceplatform.domain

logging:
  level:
    com.yiduofar.serviceplatform.mapper: debug

server:
  port: 8088

  
  #============================================================================
  # netty socket io setting
  #============================================================================
  # host在本地测试可以设置为localhost或者本机IP，在Linux服务器跑可换成服务器IP
socketio:
  host: localhost
  port: 9099
  # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxFramePayloadLength: 1048576
  # 设置http交互最大内容长度
  maxHttpContentLength: 1048576
  # socket连接数大小（如只监听一个端口boss线程组为1即可）
  bossCount: 1
  # 连接数大小
  workCount: 100
  # 允许客户请求
  allowCustomRequests: false
  # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
  upgradeTimeout: 1000000
  # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  pingTimeout: 6000000
  # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
  pingInterval: 25000

application:
  version: 1.0.0.0
  formatted-version: v1.0.0.0
  title: 校园组队与信息服务平台
spring-boot:
  version: 2.7.4.RELEASE
  formatted-version: v2.7.4.RELEASE

