spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/graduation_project_db?useUnicode=true&charactorEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: "root"
    password: ""
    hikari:
      pool-name: DateHikariCP # ????
      minimum-idle: 5 # ???????
      idle-timeout: 1800000 # ?????????????600000?10???
      maximum-pool-size: 10 # ????????10
      auto-commit: true # ?????????????
      max-lifetime: 1800000 # ?????????0?????????1800000?30???
      connection-timeout: 30000 # ?????????30000?30??
      connection-test-query: SELECT 1 # ?????????????

  mvc:
    static-path-pattern: /static/**

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ayi.seckill.domain

logging:
  level:
    com.ayi.seckill.mapper: debug

server:
  port: 8088